openapi: 3.0.0
info:
  title: AG Station
  version: "1.0"
  description: "AG Stationに関するAPIです"
servers:
  - url: http://localhost:4000
    description: localhost
tags:
  - name: default
paths:
  /start.m3u8:
    get:
      tags: ["default"]
      summary: ffmpeg等へ録画を始めるためのm3u8ファイルを提供します
      description: ffmpeg等へ録画を始めるためのm3u8ファイルを提供します
      responses:
        "200":
          description: "m3u8ファイルを返却"
          content:
            application/vnd.apple.mpegurl:
              schema:
                type: "string"
                example: "#EXTM3U\n#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=242455\nhttp://localhost:${port}/aandg1.m3u8"
  /aandg1.m3u8:
    get:
      tags: ["default"]
      summary: ffmpeg等へA&Gサーバからの内容を書き換えて最新のm3u8ファイルを提供します
      description: ffmpeg等へA&Gサーバからの内容を書き換えて最新のm3u8ファイルを提供します
      responses:
        "200":
          description: "m3u8ファイルを返却"
          content:
            application/vnd.apple.mpegurl:
              schema:
                type: "string"
        "500":
          description: "バックエンド処理エラー発生時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                example: { error: "ERROR!! occurred in Backend." }
  /record:
    get:
      tags: ["default"]
      summary: ffmpegで録画を実行
      description: ffmpegで録画コマンドを実行します
      parameters:
        - in: query
          name: time
          required: true
          description: 録画する長さ（秒）
          schema:
            type: number
        - in: query
          name: name
          required: true
          description: 動画ファイルの名前
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                example: { message: "OK" }
        "400":
          description: "パラメータ不足時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                example: { error: "timeとnameパラメータを指定してください．" }
  /schedule:
    get:
      tags: ["default"]
      summary: 予約録画を受け付ける
      description: 予約録画を受け付ける
      parameters:
        - in: query
          name: name
          required: true
          description: 番組名
          schema:
            type: string
        - in: query
          name: start
          required: true
          description: 開始時刻（例：2021-09-27T11:23:30）
          schema:
            type: string
        - in: query
          name: length
          required: true
          description: 録画する長さ（秒）
          schema:
            type: number
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                example: { message: "OK" }
        "400":
          description: "パラメータエラー時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                example:
                  { error: "length,name,startパラメータを指定してください．" }
  /scheduleInfo:
    get:
      tags: ["default"]
      summary: 予約情報を返却
      description: 予約情報を返却
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: UUID
                  program_name:
                    type: "string"
                    description: 番組名
                  start_time:
                    type: "string"
                    description: 録画開始時間（UTC）
                  program_length:
                    type: "number"
                    description: 番組の長さ（秒）
                  recorded:
                    type: "boolean"
                    description: 録画ジョブ実行済みか
                example:
                  [
                    {
                      "id": "288d6cf2-4c3c-4dec-ba11-942bebc78197",
                      "program_name": "矢野・小南 絵物語WA-GEI",
                      "start_time": "2021-10-02T08:00:00.000Z",
                      "program_length": 1800,
                      "recorded": false,
                    },
                    {
                      "id": "3a93c995-1832-41ac-ba97-444d7b46526b",
                      "program_name": "オトメフラグラジオ（仮）",
                      "start_time": "2021-10-02T06:30:00.000Z",
                      "program_length": 1800,
                      "recorded": false,
                    },
                    {
                      "id": "9660ce1f-b574-4549-8cc3-49c8d015e9d6",
                      "program_name": "鈴木みのりと笑顔満タンで！",
                      "start_time": "2021-10-02T06:00:00.000Z",
                      "program_length": 1800,
                      "recorded": true,
                    },
                    {
                      "id": "e1e710c7-db67-499b-942a-996d6cc8d4ef",
                      "program_name": "学園祭学園プレゼンツ 喋れ！学園祭",
                      "start_time": "2021-10-02T07:30:00.000Z",
                      "program_length": 1800,
                      "recorded": false,
                    },
                    {
                      "id": "f96aca9d-8ffb-41ec-846b-e8d85631d2da",
                      "program_name": "22/7（ナナブンノニジュウニ）割り切れないラジオ+",
                      "start_time": "2021-10-02T07:00:00.000Z",
                      "program_length": 1800,
                      "recorded": false,
                    },
                  ]
  /scheduleCancel:
    delete:
      tags: ["default"]
      summary: 番組の録画予約を消去
      description: 番組の録画予約を消去します
      parameters:
        - in: query
          name: id
          required: true
          description: 消去する番組のUUID
          schema:
            type: number
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                example: { message: "OK" }
        "400":
          description: "パラメータエラー時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                example:
                  {
                    error: "idパラメータが不正です．/scheduleInfo で取得できるIDを指定してください．",
                  }
